name: Test

on:
  push:
    branches:
      - main

jobs:
  save_vars:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.set-vars.outputs.name }}
      job: ${{ steps.set-vars.outputs.job }}
    steps:
      - name: Save variables
        id: set-vars
        run: |
          echo "name=Jerm" >> $GITHUB_OUTPUT
          echo "job=None" >> $GITHUB_OUTPUT

  use_vars:
    needs: save_vars
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo "Name: ${{ needs.save_vars.outputs.name }}"
          echo "Job: ${{ needs.save_vars.outputs.job }}"
