name: Test

on:
  push:
    branches:
      - main

jobs:
  save_vars:
    uses: ./.github/workflows/save_vars.yml

  use_vars:
    needs: save_vars
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo "Name: ${{ needs.save_vars.outputs.name }}"
          echo "Job: ${{ needs.save_vars.outputs.job }}"
